### ISSUE TITLE
Fix Readme.md prerequisites

### ISSUE THREAD

**Issue by SinnoTogo** [TexasInstruments/ti-bdebstrap#28]
Under the prerequisites of the Readme.md document we have the next line:
pip3 install toml-cli

It shall be changed to:
sudo pip3 install toml-cli

since the build script is run as sudo.

Also had to run the next command to add the keyrings for ti-debpks:
curl -fsSL https://texasinstruments.github.io/ti-debpkgs/KEY.gpg | sudo gpg --dearmor -o /usr/share/keyrings/ti-debpkgs.gpg

Last but not least also had to run:
sudo pip3 install jsonschema

**Comment by sskartheekadivi** [comment]
- Prerequisites have been updated
- ti-debpkgs keyring is no longer needed to be added on host.
