### ISSUE TITLE
Version 09.01.00.008 build update

### ISSUE THREAD

**Issue by MMetelko** [TexasInstruments/ti-bdebstrap#38]
The latest TI AM64 SDK software download is version `09.02.00.08` and the documentation here points to latest version number (`am62-bookworm-09.02.00.008`), but the latest version in the `builds.toml` is `09.02.00.001`.  Are there any other updates for the latest release?

**Comment by sskartheekadivi** [comment]
Hey @MMetelko, Thanks for bringing this up.
The current versions should've been 09.02.01.xx instead of 09.02.00.xx. We'll update it.

**Comment by sskartheekadivi** [comment]
The versions have been updated. Hence, closing this issue.

Thanks @MMetelko, Keep reporting issues. :)
