### ISSUE TITLE
Is there a tool to create .wic file from build results?

### ISSUE THREAD

**Issue by MMetelko** [TexasInstruments/ti-bdebstrap#44]
I really like this tool for allowing customization of an image for the AM64x.  I see the `create-sdcard.sh` for directly creating an SD card image.  I am building the image on a remote system and would like to download an complete image that I can flash onto an SD card using tools like balenaEtcher.  Is there a script available that will take the resulting partition files (bsp_source, boot and rootfs) and create the `.wic` file (like the one downloadable from the SDK download page?

**Comment by sskartheekadivi** [comment]
Hi @MMetelko ,

I'm currently working on it and close to completion. Will create a PR after some testing.
