### ISSUE TITLE
Bootable image for AM64x using wic create script needs tiboot3.bin

### ISSUE THREAD

**Issue by MMetelko** [TexasInstruments/ti-bdebstrap#46]
Thank you very much for adding the `create-wic.sh` script.  I was able to create a .wic file and transfer it to an SD card.  But, the AM64x system did not boot (no UART output at all).  So, I looked at the boot partition and did not see the `tiboot3.bin` file needed.  Since the original image (downloaded from the SDK page) had this file available, I copied it and put it on the new SD drive and the system was able to boot up.  Given the `builds.toml` file references AM62 and AM64 configurations, I am guessing that this repo is intended to serve as image customization for both systems.  It would be good to include information on where to obtain valid versions of the `tiboot3.bin` file for the different systems or reference the appropriate TI documentation about how to find it.  In our own development, one of us is using an AM64A (GP) board and the other is using an AM64B (HS-FS) board.  So, we know to change the `tiboot3.bin` to files that reference the GP and HS-FS setup since the downloadable image defaults to the AM64-evm boot configuration (HS-evm).

**Comment by glneo** [comment]
Thanks for the bug report, seem like that file needs copied in the script, I'll let @sskartheekadivi comment on that.

Side comment, we no longer support the original AM64A (GP) boards, and I thought we had exchanged them all for the new AM64B (HS-FS) models (AM64A was a limited early access run). Support for AM64A in the downloadable images will be dropped in the next SDK also. Let me reach out internally to find the steps to getting your board upgraded.

**Comment by MMetelko** [comment]
@glneo Upgrading our two AM64A boards would be very much appreciated.

**Comment by sskartheekadivi** [comment]
@MMetelko , Can you share your log file that's saved in `logs/`.

**Comment by MMetelko** [comment]
It does look like there was an issue building the tiboot3.bin.  I have also attached the full log.
[am64-bookworm-09.02.01.006-rt.log](https://github.com/TexasInstruments/ti-bdebstrap/files/14605027/am64-bookworm-09.02.01.006-rt.log)

```
  LD      spl/u-boot-spl
  OBJCOPY spl/u-boot-spl-nodtb.bin
  SYM     spl/u-boot-spl.sym
  CAT     spl/u-boot-spl-dtb.bin
  COPY    spl/u-boot-spl.bin
  BINMAN  .binman_stamp
binman: Unknown entry type 'ti-board-config' in node '/binman/board-cfg/ti-board-config' (expected etype/ti_board_config.py, error 'No module named 'jsonschema''
make[1]: *** [/var/lib/jenkins/workspace/RIAPS_riaps-ti-bdebstrap_develop/build/am64-bookworm-09.02.01.006-rt/bsp_sources/ti-u-boot/Makefile:1108: .binman_stamp] Error 1
make[1]: Leaving directory '/var/lib/jenkins/workspace/RIAPS_riaps-ti-bdebstrap_develop/build/am64-bookworm-09.02.01.006-rt/bsp_sources/ti-u-boot/out/r5'
make: *** [Makefile:177: sub-make] Error 2
cp: cannot stat '/var/lib/jenkins/workspace/RIAPS_riaps-ti-bdebstrap_develop/build/am64-bookworm-09.02.01.006-rt/bsp_sources/ti-u-boot/out/r5/tiboot3*.bin': No such file or directory
```

**Comment by glneo** [comment]
Looks like we have missing dependencies in the README, fixed here https://github.com/TexasInstruments/ti-bdebstrap/pull/47/commits/d18b1086e80b5484c2c5ea775232b8589b1946c1

Could you try to see if this fixes it?:

```
sudo apt install python3-pyelftools python3-pip python3-dev python3-yaml python3-jsonschema python3-cryptography
```

**Comment by MMetelko** [comment]
Looks like I was missing `python3-jsonschema`.  I rebuilt the image and saw the tiboot files available.  I have successfully loaded it on the board.  Thank you so much for your quick assistance!

**Comment by MMetelko** [comment]
@glneo Did you find out what steps we can take to replace the AM64A (GP) boards we have with the supported AM64B (HS-FS) models?  Please guide me in a direction for this is possible.

**Comment by glneo** [comment]
Hi @MMetelko , yes, could you reach out directly to my work email (afd at ti.com) so I can get your contact details and where to send the boards.
